# Generated by Django 5.2 on 2025-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='design_payments/'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
