# Generated by Django 5.2 on 2025-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_designrequest_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
