# Generated by Django 5.2 on 2025-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_designrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_images/'),
        ),
    ]
