# Generated by Django 5.2 on 2025-05-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_designpackage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='designrequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Required if you are not logged in', max_length=254),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='quote_token',
            field=models.CharField(blank=True, help_text='Unique token for guest quote access', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
