# Generated by Django 5.2 on 2025-12-09 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_designrequest_options_designrequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='full_name',
            field=models.CharField(blank=True, help_text='Client name', max_length=150),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number for WhatsApp updates', max_length=20),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
