# Generated by Django 5.2 on 2026-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_designrequest_full_name_designrequest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='brand_colors',
            field=models.CharField(blank=True, help_text='Main brand colors (e.g., #FF5733, Blue, Red)', max_length=200),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design_preferences',
            field=models.TextField(blank=True, help_text='Any specific design style preferences?'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='inspiration_links',
            field=models.TextField(blank=True, help_text='Links to designs you like (one per line)'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Who is your target audience?'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='timeline_preference',
            field=models.CharField(blank=True, choices=[('rush', 'Rush (1-2 days)'), ('standard', 'Standard (3-5 days)'), ('flexible', 'Flexible (1-2 weeks)')], help_text='When do you need this completed?', max_length=50),
        ),
    ]
