# Generated by Django 5.2 on 2026-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_discount_amount_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_backorder',
            field=models.BooleanField(default=False, help_text='Allow orders when out of stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Enable inventory tracking for this product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'),
        ),
    ]
